// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog/blog.proto

package kz.mircella.grpc.blog;

public interface ReadBlogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.ReadBlogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  boolean hasBlog();
  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  kz.mircella.grpc.blog.Blog getBlog();
  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  kz.mircella.grpc.blog.BlogOrBuilder getBlogOrBuilder();
}
