// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather/weather.proto

package kz.mircella.grpc.weather;

public interface HumidityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.Humidity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double percentage = 1;</code>
   */
  double getPercentage();
}
