// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather/weather.proto

package kz.mircella.grpc.weather;

public interface TemperatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.Temperature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double degree = 1;</code>
   */
  double getDegree();

  /**
   * <code>.weather.Temperature.Unit unit = 2;</code>
   */
  int getUnitValue();
  /**
   * <code>.weather.Temperature.Unit unit = 2;</code>
   */
  kz.mircella.grpc.weather.Temperature.Unit getUnit();
}
