// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather/weather.proto

package kz.mircella.grpc.weather;

public interface WeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.WeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 longitude = 1;</code>
   */
  int getLongitude();

  /**
   * <code>int32 latitude = 2;</code>
   */
  int getLatitude();
}
