// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator/calculator.proto

package kz.mircella.grpc.calculator;

public interface ComputeAverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.ComputeAverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double average = 1;</code>
   */
  double getAverage();
}
