// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator/calculator.proto

package kz.mircella.grpc.calculator;

public interface FindMaximumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.FindMaximumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
