// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication/demo.proto

package kz.mircella.grpc.demo;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_FibonacciRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_FibonacciRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_FibonacciResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_FibonacciResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_FactorialRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_FactorialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authentication_FactorialResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authentication_FactorialResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031authentication/demo.proto\022\016authenticat" +
      "ion\"!\n\020FibonacciRequest\022\r\n\005value\030\001 \001(\005\"\"" +
      "\n\021FibonacciResponse\022\r\n\005value\030\001 \001(\005\"!\n\020Fa" +
      "ctorialRequest\022\r\n\005value\030\001 \001(\005\"\"\n\021Factori" +
      "alResponse\022\r\n\005value\030\001 \001(\0052\265\001\n\013DemoServic" +
      "e\022R\n\tFibonacci\022 .authentication.Fibonacc" +
      "iRequest\032!.authentication.FibonacciRespo" +
      "nse\"\000\022R\n\tFactorial\022 .authentication.Fact" +
      "orialRequest\032!.authentication.FactorialR" +
      "esponse\"\000B\031\n\025kz.mircella.grpc.demoP\001b\006pr",
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authentication_FibonacciRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authentication_FibonacciRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_FibonacciRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_authentication_FibonacciResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authentication_FibonacciResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_FibonacciResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_authentication_FactorialRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authentication_FactorialRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_FactorialRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_authentication_FactorialResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_authentication_FactorialResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authentication_FactorialResponse_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
