// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication/demo.proto

package kz.mircella.grpc.demo;

public interface FactorialRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication.FactorialRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
