// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcdcalculator/gcdcalculator.proto

package kz.mircella.grpc.gcdcalculator;

public interface GCDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gcdcalculator.GCDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 gcd = 1;</code>
   */
  int getGcd();
}
