// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet/greet.proto

package kz.mircella.grpc.greet;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  boolean hasGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  kz.mircella.grpc.greet.Greeting getGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  kz.mircella.grpc.greet.GreetingOrBuilder getGreetingOrBuilder();
}
